server:
  port: 9090

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: greet-service
          uri: http://localhost:8082
          predicates:
            - Path=/greet-service/**
